package com.example.randomalarm.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.randomalarm.setting.AlarmSettingInfo;
import com.example.randomalarm.setting.DefaultSetting;

import com.example.randomalarm.greendao.db.AlarmSettingInfoDao;
import com.example.randomalarm.greendao.db.DefaultSettingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig alarmSettingInfoDaoConfig;
    private final DaoConfig defaultSettingDaoConfig;

    private final AlarmSettingInfoDao alarmSettingInfoDao;
    private final DefaultSettingDao defaultSettingDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        alarmSettingInfoDaoConfig = daoConfigMap.get(AlarmSettingInfoDao.class).clone();
        alarmSettingInfoDaoConfig.initIdentityScope(type);

        defaultSettingDaoConfig = daoConfigMap.get(DefaultSettingDao.class).clone();
        defaultSettingDaoConfig.initIdentityScope(type);

        alarmSettingInfoDao = new AlarmSettingInfoDao(alarmSettingInfoDaoConfig, this);
        defaultSettingDao = new DefaultSettingDao(defaultSettingDaoConfig, this);

        registerDao(AlarmSettingInfo.class, alarmSettingInfoDao);
        registerDao(DefaultSetting.class, defaultSettingDao);
    }
    
    public void clear() {
        alarmSettingInfoDaoConfig.clearIdentityScope();
        defaultSettingDaoConfig.clearIdentityScope();
    }

    public AlarmSettingInfoDao getAlarmSettingInfoDao() {
        return alarmSettingInfoDao;
    }

    public DefaultSettingDao getDefaultSettingDao() {
        return defaultSettingDao;
    }

}
