package com.example.randomalarm.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.randomalarm.setting.AlarmSettingInfo;
import com.example.randomalarm.song.Song;

import com.example.randomalarm.greendao.db.AlarmSettingInfoDao;
import com.example.randomalarm.greendao.db.SongDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig alarmSettingInfoDaoConfig;
    private final DaoConfig songDaoConfig;

    private final AlarmSettingInfoDao alarmSettingInfoDao;
    private final SongDao songDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        alarmSettingInfoDaoConfig = daoConfigMap.get(AlarmSettingInfoDao.class).clone();
        alarmSettingInfoDaoConfig.initIdentityScope(type);

        songDaoConfig = daoConfigMap.get(SongDao.class).clone();
        songDaoConfig.initIdentityScope(type);

        alarmSettingInfoDao = new AlarmSettingInfoDao(alarmSettingInfoDaoConfig, this);
        songDao = new SongDao(songDaoConfig, this);

        registerDao(AlarmSettingInfo.class, alarmSettingInfoDao);
        registerDao(Song.class, songDao);
    }
    
    public void clear() {
        alarmSettingInfoDaoConfig.clearIdentityScope();
        songDaoConfig.clearIdentityScope();
    }

    public AlarmSettingInfoDao getAlarmSettingInfoDao() {
        return alarmSettingInfoDao;
    }

    public SongDao getSongDao() {
        return songDao;
    }

}
